### ISSUE TITLE
Jeb_ axolotl

### ISSUE THREAD

**Issue by Flamgop** [dbrighthd/creatures#11]
axolotl jeb

**Comment by dbrighthd** [comment]
GOD DAMMIT FLAMGOP STEALING MY THUNDER THATS LITERALLY WHAT I WAS WORKING ON

**Comment by Flamgop** [comment]
deal with it

**Comment by dbrighthd** [comment]
https://user-images.githubusercontent.com/68525639/129981525-b9e805a1-730f-454f-bf6b-0f3c028d82db.mp4

**Comment by dbrighthd** [comment]
I dont know what the framerate is so jittery
